# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/enzof/OneDrive/Desktop/Basys-3-XADC-2018.2-3/vivado_proj/Basys-3-XADC.srcs/sources_1/ip/c_counter_binary_0/c_counter_binary_0.xci
# IP: The module: 'c_counter_binary_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/enzof/OneDrive/Desktop/Basys-3-XADC-2018.2-3/vivado_proj/Basys-3-XADC.gen/sources_1/ip/c_counter_binary_0/c_counter_binary_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_counter_binary_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/enzof/OneDrive/Desktop/Basys-3-XADC-2018.2-3/vivado_proj/Basys-3-XADC.srcs/sources_1/ip/c_counter_binary_0/c_counter_binary_0.xci
# IP: The module: 'c_counter_binary_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/enzof/OneDrive/Desktop/Basys-3-XADC-2018.2-3/vivado_proj/Basys-3-XADC.gen/sources_1/ip/c_counter_binary_0/c_counter_binary_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_counter_binary_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
